#!/usr/bin/env bash

LICENSE='The MIT License (MIT)

Copyright (c) 2016 Tosh Afanasiev <tosh@tosh.me>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.'

GOVERSION=$1
FNAME=go$GOVERSION.linux-amd64.tar.gz
CACHEDIR=~/.getgo
ONAME=$CACHEDIR/$FNAME
URL=https://storage.googleapis.com/golang/$FNAME
DNAME=/usr/local/go$GOVERSION/

if [ -z "$GOVERSION" ]; then
    echo "usage: $0 GOVERSION"
    echo "example: $0 1.5.3"
    exit 1
fi

# make sure the cache dir exists
[ -d $CACHEDIR ] || mkdir -p $CACHEDIR &> /dev/null

# try to download straight into the cache dir
[ -f $ONAME ] || curl --fail -o $ONAME $URL || exit $?

# if the dir's there it's assumed that it's all intact
if [ ! -d $DNAME ]; then
	mkdir -p $DNAME
	# this assumes the tarball has a root directory which needs removing
	tar xzf $ONAME -C $DNAME --strip-components=1
fi

# the distributions in the tarballs expect to be
# installed here so you don't need to set GOROOT
rm /usr/local/go
ln -s $DNAME /usr/local/go

